### PR TITLE
Add flex to Jemdoc

### PR DESCRIPTION
**Pull request by rikhuijzer**
This pull request contains two changes, namely

1. the whole page is now contained in a flex box such that it will (horizontally) center on big screens;
2. on small screens, the menu is shown above the page content instead of on the left

For small screens, I have considered the typical menu button to allow the user to trigger the menu by clicking. However, this would either introduce Javascript or very arcane CSS styling. Overall, I think just showing the menu above the page isn't too bad and might be even the most clear for end-users.

### CODE REVIEW

**Comment by tlienart** [comment]
thanks a lot!! I'll try this soon and should merge it by tomorrow :)

**Comment by rikhuijzer** [comment]
Yes, I was considering to mention that I only tested it on my desktop and iPhone. Let me know if you find any issue

**Comment by tlienart** [comment]
Some suggestions:

```
diff --git a/src/templates/jemdoc/_css/jemdoc.css b/src/templates/jemdoc/_css/jemdoc.css
index 3040cf8..cffb7ed 100644
--- a/src/templates/jemdoc/_css/jemdoc.css
+++ b/src/templates/jemdoc/_css/jemdoc.css
@@ -7,9 +7,14 @@
     }
 
     .layout-menu {
+      margin: 0;
+      margin-top: 2rem;
       padding-left: 2em;
       padding-right: 2em;
     }
+    .franklin-content h1 {
+      margin-top: 0;
+    }
   }
 
 @media (min-width: 750px) {
@@ -19,6 +24,10 @@
     justify-content: center;
     margin: auto;
   }
+  .layout-menu{
+    margin-top: 5rem;
+    margin-left: 1rem;
+  }
 }
 
 body {
```

**Comment by rikhuijzer** [comment]
Thanks for the suggestions. I've added them.

> this keeps the menu kind of aligned with the h1 of the page which I think looks better 
Agreed, that was a bit odd. I was also considering doing something about it.

> otherwise looks great, thanks!
You're welcome. It was surprisingly easy actually.

**Comment by tlienart** [comment]
Fantastic, thanks Rik!

**Pull request merged**
