### PR TITLE
Add the celeste template

### PR DESCRIPTION
**Pull request by tlnagy**
This PR adds support for the [Celeste](https://github.com/nicoelayda/celeste) Jekyll template. This is a really nice clean template optimal for a blog, etc.

image

Running on `Franklin.jl`:

Screenshot from 2022-06-14 14-40-03

### CODE REVIEW

**Comment by tlienart** [comment]
very nice @tlnagy thanks!! I'll have a closer look later today

**Comment by tlnagy** [comment]
bump @tlienart. Anything else needed here?

**Comment by tlienart** [comment]
Hello! yep I've not forgotten about this, just need to find some time to play a bit with it and make sure it's all good!

**Comment by tlienart** [comment]
this is a great addition, thanks so much! patch release coming soon

**Pull request merged**
