### PR TITLE
Update to highlight.js 10.7.1 

### PR DESCRIPTION
**Pull request by abelsiqueira**
Related to https://github.com/tlienart/Franklin.jl/pull/803 and https://github.com/tlienart/Franklin.jl/pull/804.

I chose the custom download from https://highlightjs.org/download/ selecting all Common (were already selected) and `Julia` and `Julia REPL` from the Other.

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks a lot!

This one is a bit trickier, in terms of languages I typically pick https://github.com/tlienart/FranklinTemplates.jl#misc but that's easy to adjust. 

The javascript by default doesn't recognise `shell>` and `pkg>` so there needs to be a fix for this as per this line: https://github.com/tlienart/FranklinTemplates.jl/blob/master/src/templates/common/_libs/highlight/highlight.pack.js#L639 
in that line you'll see that it's basically a copy-paste of the `Julia>` one 2 times (once for shell, once for pkg). Depending on highlight version the exact syntax to copy paste is a bit different (basically you have to search for the Julia one, and then copy paste).

I don't want to bother you with this though, I'm already grateful for your two PRs! I can do that fix in a bit.

**Comment by abelsiqueira** [comment]
Hi @tlienart, happy to help. I updated the PR with the different highlight custom package and added the `shell>` and `pkg>` syntax copies. There was a new `aliases:["jldoctest"]` for the original, which I didn't know if I should copy or not, so I left it out. The commits are separated for better verification.
I imagine it's hard to make sure I did the right, so feel free to close or modify this PR.

**Comment by tlienart** [comment]
Thanks a lot!

No it's not hard to verify: we just have to locally create a new site with the default template and check the second menu page (`/menu2/`) (maybe menu 3 one of the two) and check that the code is highlighted properly (there's a few toy code with `shell>` and `pkg`

Thanks again for your help!

**Comment by abelsiqueira** [comment]
Looks like it worked:
franklin-template
- I `dev`'ed into the `FranklinTemplate` folder
- `newsite("friedpotato")`
- The `highlight.pack.js` from fried potato shows 10.7.1
- serving, nothing appears broken.

**Comment by tlienart** [comment]
Perfect, thank you very much!

**Pull request merged**
